language: node_js

node_js:
  - 12
  - 11
  - 10
  - 8

sudo: false

cache: npm

env:
  global:
    - secure: e+9du4YobFLpfGpxFVn2oQcUfaCERTrwAx2HPbVIe173GdSwaeag8PWCbeoLPGGqbVvrqMIjtiSv6QgydiKISmDkMhuwQr43r1q/fSEMveUGW1AJbV6JwvtMQVAoU00BysKh4X45NzIDk5S18x5MTOyp7ZeWt8U+VD+hRuFF6wV3EmeWSAurxVC261m8QGs4V3RmSOveNuMjWH96PA4RzbUk3zJffxfJ6e8wr+WJkaHaxWUFsbYAPgMj9iUhJg8obvRIBJZA2oFyW7YX/UTxH3XRwXbljRqkkpSWTH3T/qlL4/F8PF9Wjv9KyfXYa985VU+L5AlwHKfx4zP8ClUbZNdFelFLfILtwgg9gmtW8fs0rMAcFU6sscvjk3hw8ny87HhTW/W6oHrroY8N71mOUXWvjN66tpQQieGwvl878l0N39mQUG8XUzxHLPYiPUfpZFe7a/kpaF1wh1l8agD+4aYTyK5ah8HcYpToQScUiVYdscuZcqj4lJT+VT0EgfM21/htx55UKseV3uhMSgxPczj95jdAzA/NwgEv2mVdnRCEFTzH7FaC4IMgTN979vJHJseHPI5Sxzs0BvzjJ30GgKQlmSHby1uO3v4qVtThKU8wiLBOrJAp+G6lTGS082ki9A8YvNVAQI6XDFV3OcwPE+mKBnfftbjduSKCHx8cdO8=

script:
  - npm run lint
  - npm test

after_script:
  - npm run cover
  - cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
